spring:
  application:
    name: microservice-consumer-movie-ribbon-with-hystrix
server:
  port: 8010
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka,http://user:password123@localhost:8760/eureka
  instance:
    prefer-ip-address: true
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
logging:
  level:
    com: debug